runtime: python39
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
  target_throughput_utilization: 0.6

entrypoint: gunicorn -b :$PORT simple_bot:app

env_variables:
  BOT_TOKEN: "7227637125:AAFYcYk68mqvqJ7DJdFZgX9txtTvUpeWCIo" 